jwt:
  secret: eccb33208298cea51c29db8f926b9146213eccb33208298cea51c29db8f926b9146123eccb33208298cea51c29db8f926b9146123eccb33208298cea51c29db8f926b9146123eccb33208298cea51c29db8f926b9146123eccb33208298cea51c29db8f926b9146
  expiration: 3600
spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    port: 465
    username: xxx
    password: xxx  # 网易邮箱的授权码，非登录密码
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  # redis配置
  data:
    redis:
      port: 6379
      host: ***REMOVED***
      database: 0
      password: xxx
      username: xxx